name: 'housamoAutoLogin'

on:

  schedule:

    - cron: '0  0,7,15,23 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout

      uses: actions/checkout@master

    - name: Set up Python #安装python

      uses: actions/setup-python@v1

      with:

        python-version: 3.8

    - name: Install requests #安装requests

      run: pip install requests

    - name: Read anth_key & Login  #读取账号并登录

      env: 

        auth_keys: ${{ toJson(secrets) }}   # 由secrets 提供auth_key

      run: python Login.py
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
name: 'housamoAutoLogin'

on:
  schedule:
    - cron: '0  0,7,15,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: pip install requests
    - name: Read anth_key & Login  #读取账号并登录
      env: 
        auth_keys: ${{ toJson(secrets) }}   # 由secrets 提供auth_key
      run: python Login.py
